### ISSUE TITLE
How to change the internal URL domain?

### ISSUE THREAD

**Issue by shafiemukhre** [jgazeau/website2pdf#31]
The internal urls in the contents are default to https://localhost:1313 which is understandable since I'm running locally. Now, the internal links will go the localhost url instead of the actual url page. Is there a way to change all these href address for the internal anchor tag to the base url of the actual website (either using javascript or hugo)? 

I tried using javascript after the Dom loaded but it doesn't work, it seems this script generated the pdf page from the html pages that hugo built

**Comment by jgazeau** [comment]
Hi @shafiemukhre ,

Indeed I've put the `localhost:1313` default sitemapUrl as the main purpose was to run the generation in a CI and based on a Hugo website.

In your case, if I understand well you would like to print the page of a deployed website right ?
In that case just use the `sitemap-url` option to point to the sitemap of your deployed website instead of your localhost.
For example you can do something like that:
```
npx run website2pdf --sitemap-url https://shadocs.netlify.app/sitemap.xml
```

Also just to mention, as at first the purpose was to print a whole Hugo website, the generation is based on the sitemap protocol (the default one used by Hugo). I'll try to add in the future the possibility to print an array of url and not rely inevitably on a sitemap.

**Comment by jgazeau** [comment]
Hi @shafiemukhre,
I think I didn't correctly understand your issue at first 😕.
What you are trying to achieve is quite particular. Indeed the pdf is generated from the html pages generated, so in your case I see two solutions:
* you can actually generate PDF from a deployed website (check my previous comment). So in your case, if you want to generate PDF that contains link of your production environment for example, you can directly generate PDF from this production environment
* you have to use the real links within your hugo content to generate proper html (or also use a script or a tool to change the html content before being served on your localhost). But this solution would require to modify all your links, and furthermore it would only make sense for pdf generation, because in local or any environment, you want relative links instead of absolute links.
Apart from that I don't see any other simpler solution.
