### ISSUE TITLE
[bug]: Target Closed in version 0.0.8

### ISSUE THREAD

**Issue by pankajgupta1206** [jgazeau/website2pdf#48]
### Steps that lead to the issue

We are currently getting below error in new version (0.0.8) while running in gitlab pipeline .  Please check if it can be fixed . 

/src/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:298
                error: new Errors_js_1.ProtocolError(),
                       ^
ProtocolError: Protocol error (IO.read): Target closed.
    at /src/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:298:24
    at new Promise (<anonymous>)
    at CDPSession.send (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:294:16)
    at Readable.read [as _read] (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/util.js:401:43)
    at Readable.read (node:internal/streams/readable:487:10)
    at createAsyncIterator (node:internal/streams/readable:1131:54)
    at createAsyncIterator.next (<anonymous>)
    at getReadableAsBuffer (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/util.js:366:26)
    at async Page.pdf (/src/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2079:24)
    at async Promise.all (index 2) {
  originalMessage: ''
}

### Expected behavior

Exception should not be there . 

### Reproducer

Currently not able to resolve even after having multiple retries.

**Comment by pankajgupta1206** [comment]
Please let me know if there is any updates on this issue.

**Comment by jgazeau** [comment]
Hi, 
The problem is coming from puppeteer and is probably due to a lack of resources available. 
I suggest you to check this [thread](https://stackoverflow.com/questions/51629151/puppeteer-protocol-error-page-navigate-target-closed) and especially the options used in this [answer](https://stackoverflow.com/a/66644276).
As mention in the README of website2pdf you can use the `chromiumFlags` option to set the puppeteer options used when starting the chromium instance.
Another option would be to check and use a runner with more resources to see if it solve your problem.

**Comment by pankajgupta1206** [comment]
I agree but why this issue is existing with latest version (0.0.8) only.

**Comment by jgazeau** [comment]
IDK, maybe because puppeteer has been updated ? In website2pdf the code related to puppeteer hasn't changed between 0.0.6 and 0.0.8, and in the 0.0.6 only possibility do set puppeteer options has been introduced, so users can manage the launch on their own.

**Comment by pankajgupta1206** [comment]
Hi Jordan, 

I tried with below chromium flag option but nothing is working out . Please let me know if it can be done at website2pdf api end . 

--chromiumFlags="--no-sandbox --disable-dev-shm-usage"

**Comment by jgazeau** [comment]
Hi,
Nothing that can be done in website2pdf actually.
Can you check if it is working locally ? And did you check by running it in a gitlab runner having more resources ?

**Comment by pankajgupta1206** [comment]
It is working locally and even working with project having less content doc but creating exception when content doc are more.

**Comment by jgazeau** [comment]
Hi @pankajgupta1206 ,
I have check on my own projects and indeed  there is an issue, because the library is trying to load too much pages at once, which leads to memory issue if you are trying to print a site containing lot of pages.
I will modify the library to parallelize the process using a pool of promises, with a default value, and a user option to change it.
I should be able to do it this week and release it afterwards.

**Comment by pankajgupta1206** [comment]
Thanks Jordan , It is working fine now.
