### ISSUE TITLE
[question]: change base URL of links in PDFs

### ISSUE THREAD

**Issue by whyboris** [jgazeau/website2pdf#61]
### Question?

Everything is working _beautifully_ but because when generating the PDF the _website2pdf_ utility is using the _sitemap.xml_ it generates PDFs with links that look like `localhost:1313/introduction` rather than `mywebsite.com/introduction` 😅 

Is there already something I can do to fix it, or this would require a new feature? 🙇

**Comment by jgazeau** [comment]
Hi @whyboris ,
Indeed, I guess that you are using website2pdf on a local Hugo deployment of your website (port 1313 😃 ). The fact is that if you are using relative links the browser will automatically append the host in front of it. Which leads to `http://localhost:1313/introduction` if you are in local.
Unfortunately the library cannot change that, because puppeteer doesn't have that option yet ([check this issue](https://github.com/puppeteer/puppeteer/issues/3682)) and that hot changing the html is not the proper solution.

In your cases I see two solutions:
* you could change your website to set absolute links. With Hugo it could be made with a specific configuration for example. By default it would have relative links and with a website2pdf configuration it would have absolute links.
* you could generate pdfs from a deployed website that contains your appropriate links. For example using the `--sitemapUrl` option. (e.g. `website2pdf --sitemapUrl "http://mywebsite.om"` )

I'll close this issue for now but if chromium and puppeteer teams decide to add such an option I'll take that into consideration and reopen the current issue😉

**Comment by whyboris** [comment]
Thank you for the quick response 🙇 

I tried this out and it works well-enough (added to the bottom of the `baseof.html`) 👍 :
```html
    <script>

      const anchors = document.getElementsByTagName("a");

      for (let i = 0; i < anchors.length; i++) {
        const old = anchors[i].href;
        const new_url = old.replace("http://localhost:1313/", "https://utilitarianism.net/");
        anchors[i].href = new_url;
      }

    </script>
```
I'll have to add some more code to avoid messing up all the footnote links, but I'm sure it will work out 💪
